### ISSUE TITLE
Error running example

### ISSUE THREAD

**Issue by s0undt3ch** [zoldar/python-ldap-test#8]
```python
Python 2.7.11 (default, Apr 29 2016, 18:08:53) 
[GCC 5.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from ldap_test import LdapServer
>>> server = LdapServer({
...     'port': 3333,
...     'bind_dn': 'cn=admin,dc=zoldar,dc=net',
...     'password': 'pass1',
...     'base': {'objectclass': ['domain'],
...              'dn': 'dc=zoldar,dc=net',
...              'attributes': {'dc': 'zoldar'}},
...     'entries': [
...         {'objectclass': 'domain',
...          'dn': 'dc=users,dc=zoldar,dc=net',
...          'attributes': {'dc': 'users'}},
...         {'objectclass': 'organization',
...          'dn': 'o=foocompany,dc=users,dc=zoldar,dc=net',
...          'attributes': {'o': 'foocompany'}},
...     ]
... })
INFO:py4j.java_gateway:Exception while shutting down callback server
Traceback (most recent call last):
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/RaasSalt-2.7.11/lib/python2.7/site-packages/py4j/java_gateway.py", line 1654, in shutdown
    self._gateway_client.shutdown_gateway()
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/RaasSalt-2.7.11/lib/python2.7/site-packages/py4j/java_gateway.py", line 746, in shutdown_gateway
    connection = self._get_connection()
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/RaasSalt-2.7.11/lib/python2.7/site-packages/py4j/java_gateway.py", line 724, in _get_connection
    connection = self._create_connection()
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/RaasSalt-2.7.11/lib/python2.7/site-packages/ldap_test/server.py", line 80, in _create_connection
    self.auto_close, self.gateway_property)
TypeError: __init__() takes at most 3 arguments (5 given)
Traceback (most recent call last):
  File "<stdin>", line 14, in <module>
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/RaasSalt-2.7.11/lib/python2.7/site-packages/ldap_test/server.py", line 188, in __init__
    JVM_GATEWAY = run_jvm_gateway()
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/RaasSalt-2.7.11/lib/python2.7/site-packages/ldap_test/server.py", line 53, in run_jvm_gateway
    return JavaGateway(gateway_client=SlowGatewayClient(), eager_load=True)
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/RaasSalt-2.7.11/lib/python2.7/site-packages/py4j/java_gateway.py", line 1506, in __init__
    self._eager_load()
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/RaasSalt-2.7.11/lib/python2.7/site-packages/py4j/java_gateway.py", line 1553, in _eager_load
    self.jvm.System.currentTimeMillis()
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/RaasSalt-2.7.11/lib/python2.7/site-packages/py4j/java_gateway.py", line 1401, in __getattr__
    "\n" + proto.END_COMMAND_PART)
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/RaasSalt-2.7.11/lib/python2.7/site-packages/py4j/java_gateway.py", line 776, in send_command
    connection = self._get_connection()
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/RaasSalt-2.7.11/lib/python2.7/site-packages/py4j/java_gateway.py", line 724, in _get_connection
    connection = self._create_connection()
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/RaasSalt-2.7.11/lib/python2.7/site-packages/ldap_test/server.py", line 80, in _create_connection
    self.auto_close, self.gateway_property)
TypeError: __init__() takes at most 3 arguments (5 given)
>>> Gateway server started on port 25333!
```

And on python 3:
```python
Python 3.4.3 (default, Apr 29 2016, 17:41:03) 
[GCC 5.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ldap_test import LdapServer                                                                                                                                                                      
>>> server = LdapServer({
...     'port': 3333,
...     'bind_dn': 'cn=admin,dc=zoldar,dc=net',
...     'password': 'pass1',
...     'base': {'objectclass': ['domain'],
...              'dn': 'dc=zoldar,dc=net',
...              'attributes': {'dc': 'zoldar'}},
...     'entries': [
...         {'objectclass': 'domain',
...          'dn': 'dc=users,dc=zoldar,dc=net',
...          'attributes': {'dc': 'users'}},
...         {'objectclass': 'organization',
...          'dn': 'o=foocompany,dc=users,dc=zoldar,dc=net',
...          'attributes': {'o': 'foocompany'}},
...     ]
... })
INFO:py4j.java_gateway:Exception while shutting down callback server
Traceback (most recent call last):
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.4.3/lib/python3.4/site-packages/py4j/java_gateway.py", line 722, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.4.3/lib/python3.4/site-packages/py4j/java_gateway.py", line 1553, in _eager_load
    self.jvm.System.currentTimeMillis()
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.4.3/lib/python3.4/site-packages/py4j/java_gateway.py", line 1401, in __getattr__
    "\n" + proto.END_COMMAND_PART)
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.4.3/lib/python3.4/site-packages/py4j/java_gateway.py", line 776, in send_command
    connection = self._get_connection()
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.4.3/lib/python3.4/site-packages/py4j/java_gateway.py", line 724, in _get_connection
    connection = self._create_connection()
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.4.3/lib/python3.4/site-packages/ldap_test/server.py", line 80, in _create_connection
    self.auto_close, self.gateway_property)
TypeError: __init__() takes from 2 to 3 positional arguments but 5 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.4.3/lib/python3.4/site-packages/py4j/java_gateway.py", line 722, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.4.3/lib/python3.4/site-packages/py4j/java_gateway.py", line 1654, in shutdown
    self._gateway_client.shutdown_gateway()
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.4.3/lib/python3.4/site-packages/py4j/java_gateway.py", line 746, in shutdown_gateway
    connection = self._get_connection()
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.4.3/lib/python3.4/site-packages/py4j/java_gateway.py", line 724, in _get_connection
    connection = self._create_connection()
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.4.3/lib/python3.4/site-packages/ldap_test/server.py", line 80, in _create_connection
    self.auto_close, self.gateway_property)
TypeError: __init__() takes from 2 to 3 positional arguments but 5 were given
Traceback (most recent call last):
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.4.3/lib/python3.4/site-packages/py4j/java_gateway.py", line 722, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.4.3/lib/python3.4/site-packages/py4j/java_gateway.py", line 1553, in _eager_load
    self.jvm.System.currentTimeMillis()
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.4.3/lib/python3.4/site-packages/py4j/java_gateway.py", line 1401, in __getattr__
    "\n" + proto.END_COMMAND_PART)
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.4.3/lib/python3.4/site-packages/py4j/java_gateway.py", line 776, in send_command
    connection = self._get_connection()
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.4.3/lib/python3.4/site-packages/py4j/java_gateway.py", line 724, in _get_connection
    connection = self._create_connection()
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.4.3/lib/python3.4/site-packages/ldap_test/server.py", line 80, in _create_connection
    self.auto_close, self.gateway_property)
TypeError: __init__() takes from 2 to 3 positional arguments but 5 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.4.3/lib/python3.4/site-packages/py4j/java_gateway.py", line 722, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.4.3/lib/python3.4/site-packages/py4j/java_gateway.py", line 1654, in shutdown
    self._gateway_client.shutdown_gateway()
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.4.3/lib/python3.4/site-packages/py4j/java_gateway.py", line 746, in shutdown_gateway
    connection = self._get_connection()
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.4.3/lib/python3.4/site-packages/py4j/java_gateway.py", line 724, in _get_connection
    connection = self._create_connection()
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.4.3/lib/python3.4/site-packages/ldap_test/server.py", line 80, in _create_connection
    self.auto_close, self.gateway_property)
TypeError: __init__() takes from 2 to 3 positional arguments but 5 were given
Traceback (most recent call last):
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.4.3/lib/python3.4/site-packages/py4j/java_gateway.py", line 722, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 14, in <module>
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.4.3/lib/python3.4/site-packages/ldap_test/server.py", line 188, in __init__
    JVM_GATEWAY = run_jvm_gateway()
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.4.3/lib/python3.4/site-packages/ldap_test/server.py", line 53, in run_jvm_gateway
    return JavaGateway(gateway_client=SlowGatewayClient(), eager_load=True)
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.4.3/lib/python3.4/site-packages/py4j/java_gateway.py", line 1506, in __init__
    self._eager_load()
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.4.3/lib/python3.4/site-packages/py4j/java_gateway.py", line 1553, in _eager_load
    self.jvm.System.currentTimeMillis()
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.4.3/lib/python3.4/site-packages/py4j/java_gateway.py", line 1401, in __getattr__
    "\n" + proto.END_COMMAND_PART)
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.4.3/lib/python3.4/site-packages/py4j/java_gateway.py", line 776, in send_command
    connection = self._get_connection()
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.4.3/lib/python3.4/site-packages/py4j/java_gateway.py", line 724, in _get_connection
    connection = self._create_connection()
  File "/home/vampas/.dotfiles/.ext/pyenv/versions/Raas-3.4.3/lib/python3.4/site-packages/ldap_test/server.py", line 80, in _create_connection
    self.auto_close, self.gateway_property)
TypeError: __init__() takes from 2 to 3 positional arguments but 5 were given
>>> Gateway server started on port 25333!
```

**Comment by zoldar** [comment]
Closed by #9 (thanks @s0undt3ch !). Already released on PYPI:

https://pypi.python.org/pypi/python-ldap-test/0.2.2

**Comment by s0undt3ch** [comment]
Side question. I ended up fixing this because I want to have a test suite use this instead of an actual Active Directory/LDAP server, however I seem to be unable to properly populate the test LDAP server, specially, I'd like to mimic an AD tree, some elements are just ignored.

Can we configure this behavior? Are there any docs for this? Or even the java test server itself?

Thanks and sorry for these side questions...

**Comment by zoldar** [comment]
@s0undt3ch Schema validation is disabled for the test server, so there shouldn't be any problems with that. I have added a test for that, just in case:

https://github.com/zoldar/python-ldap-test/commit/870756cf105422fd6b0f9fcf301ea6de4230bbdc

If you could reproduce the issue on a concrete example, we could try sorting it out.

**Comment by s0undt3ch** [comment]
So, I finally hit this problem again...
Consider the following tree:
```python
@pytest.fixture
def ldap_server_tree():
    base = {'objectclass': ['domain'],
            'dn': 'dc=example,dc=com',
            'attributes': {'dc': 'example'}}
    entries = [
        {'ou': ['Groups'], 'objectclass': ['organizationalunit', 'top'], 'dn': 'ou=Groups,dc=example,dc=com'},
        {'ou': ['Users'], 'objectclass': ['organizationalunit', 'top'], 'dn': 'ou=Users,dc=example,dc=com'},
        {
            'ou': ['Users'],
            'roomnumber': ['123'],
            'cn': ['Admin'],
            'gidNumber': [998],
            'sn': ['Admin'],
            'homeDirectory': ['/home/admin'],
            'uidNumber': ['998'],
            'userpassword': ['admin'],
            'mail': ['admin@example.com'],
            'uid': ['admin'],
            'givenname': ['Admin'],
            'objectclass': ['person', 'inetOrgPerson', 'organizationalPerson', 'posixAccount', 'top'],
            'dn': 'uid=admin,ou=Users,dc=example,dc=com',
        },
        {
            'ou': ['Users'],
            'roomnumber': ['123'],
            'cn': ['C. R. Oldham'],
            'gidNumber': [999],
            'sn': ['Oldham'],
            'homeDirectory': ['/home/cro'],
            'uidNumber': ['999'],
            'userpassword': ['Sa1tSa1t'],
            'mail': ['cro@example.com'],
            'uid': ['cro'],
            'givenname': ['C. R.'],
            'objectclass': ['person', 'inetOrgPerson', 'organizationalPerson', 'posixAccount', 'top'],
            'dn': 'uid=cro,ou=Users,dc=example,dc=com',
        },
        {
            'dn': 'cn=SaltGroup,ou=Groups,dc=example,dc=com',
            'cn': ['SaltGroup'],
            'member': ['uid=cro,ou=Users,dc=example,dc=com'],
            'uniquemember': ['uid=cro,ou=Users,dc=example,dc=com'],
            'objectclass': ['groupOfUniqueNames', 'posixGroup', 'top'],
            'ou': ['groups']
        },
        {
            'dn': 'cn=Domain Admins,ou=Groups,dc=example,dc=com',
            'cn': ['Domain Admins'],
            'member': ['uid=cro,ou=Users,dc=example,dc=com'],
            'uniquemember': ['uid=cro,ou=Users,dc=example,dc=com'],
            'objectclass': ['groupOfUniqueNames', 'posixGroup', 'top'],
            'ou': ['groups']
        },
    ]
```
Now, let's run a search against that tree:
```python
>>> server = ldap3.Server('localhost', port=12345, use_ssl=False)
>>> conn = ldap3.Connection(server, user='uid=admin,ou=Users,dc=example,dc=com', password='admin')
>>> base_dn = 'DC=example,DC=com'
>>> search_filter = '(&(objectclass=groupofuniquenames)(cn=Domain Admins))'
>>> conn.search(search_base=base_dn, search_scope=ldap3.SUBTREE, search_filter=search_filter, attributes=['cn'])
True
>>> conn.response
[{'attributes': {'cn': ['Domain Admins']}, 'raw_attributes': {'cn': [b'Domain Admins']}, 'type': 'searchResEntry', 'dn': 'cn=Domain Admins,ou=Groups,dc=example,dc=com'}]
>>> 
>>> base_dn2 = 'cn=Domain Admins,ou=Groups,dc=example,dc=com'
>>> search_filter2 = '(|(cn=*)(member=*)(uniquemember=*))'
>>> conn.search(search_base=base_dn2, search_filter=search_filter2, attributes=['cn', 'member', 'uniquemember'])
True
>>> conn.response
[{'attributes': {'cn': ['Domain Admins']}, 'raw_attributes': {'cn': [b'Domain Admins']}, 'type': 'searchResEntry', 'dn': 'cn=Domain Admins,ou=Groups,dc=example,dc=com'}]
>>> 
```

`member` and `uniquemember` is never returned...

**Comment by s0undt3ch** [comment]
```python
>>> conn.search(search_base=base_dn2, search_filter=search_filter2, attributes=['*'])
True
>>> conn.response
[{'attributes': {'modifiersName': ['cn=Internal Root User'], 'modifyTimestamp': ['20160825092942.226Z'], 'objectClass': ['groupOfUniqueNames', 'posixGroup', 'top'], 'createTimestamp': ['20160825092942.226Z'], 'entryDN': ['cn=domain admins,ou=groups,dc=example,dc=com'], 'subschemaSubentry': ['cn=schema'], 'cn': ['Domain Admins'], 'creatorsName': ['cn=Internal Root User'], 'entryUUID': ['ae5cac7f-38ab-42ce-a1ce-d039ec500ad9']}, 'raw_attributes': {'modifiersName': [b'cn=Internal Root User'], 'modifyTimestamp': [b'20160825092942.226Z'], 'objectClass': [b'groupOfUniqueNames', b'posixGroup', b'top'], 'createTimestamp': [b'20160825092942.226Z'], 'entryDN': [b'cn=domain admins,ou=groups,dc=example,dc=com'], 'subschemaSubentry': [b'cn=schema'], 'cn': [b'Domain Admins'], 'creatorsName': [b'cn=Internal Root User'], 'entryUUID': [b'ae5cac7f-38ab-42ce-a1ce-d039ec500ad9']}, 'type': 'searchResEntry', 'dn': 'cn=Domain Admins,ou=Groups,dc=example,dc=com'}]
>>>
```
All entry attributes.

**Comment by s0undt3ch** [comment]
Of course, the users exist on the tree:
```python
>>> search_filter1 = '(&(objectclass=person)(uid=*))'
>>> conn.search(search_base=base_dn, search_filter=search_filter1, attributes=['uid'])
True
>>> conn.response
[{'attributes': {'uid': ['admin']}, 'raw_attributes': {'uid': [b'admin']}, 'type': 'searchResEntry', 'dn': 'uid=admin,ou=Users,dc=example,dc=com'}, {'attributes': {'uid': ['cro']}, 'raw_attributes': {'uid': [b'cro']}, 'type': 'searchResEntry', 'dn': 'uid=cro,ou=Users,dc=example,dc=com'}]
```

**Comment by s0undt3ch** [comment]
I think I may have found my problem... A dumb(read the docs) problem... I'll get back.

**Comment by s0undt3ch** [comment]
Yep! Extra attributes *must* be passed using `attributes`.
